# Generated by Django 4.2.2 on 2023-08-03 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_scope_of_activity_consultant_scope_of_activity_in_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultant',
            old_name='scope_of_activity_from_advertising',
            new_name='scope_of_activity_from_ads',
        ),
    ]
