# Generated by Django 4.2.2 on 2023-08-03 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_scope_of_activity_from_advertising_consultant_scope_of_activity_from_ads'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultant',
            old_name='scope_of_activity_in_profile',
            new_name='scope_of_activity',
        ),
    ]
