# Generated by Django 4.2.2 on 2023-08-03 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_consultant_agent_alter_consultant_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estates', to='home.consultant'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='neighbourhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estates', to='home.neighbourhood'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
