# Generated by Django 4.2.2 on 2023-08-03 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_estate_consultant_alter_estate_neighbourhood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
