# Generated by Django 4.2.2 on 2023-08-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_consultant_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='link',
            field=models.URLField(max_length=3000),
        ),
    ]
