# Generated by Django 4.2.2 on 2023-08-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_consultant_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='link',
            field=models.URLField(max_length=2000, unique=True),
        ),
    ]
