# Generated by Django 4.2.2 on 2023-08-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_estate_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultant',
            name='scope_of_activity_from_ads',
        ),
        migrations.AddField(
            model_name='consultant',
            name='profile',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='scope_of_activity',
        ),
        migrations.AddField(
            model_name='consultant',
            name='scope_of_activity',
            field=models.ManyToManyField(to='home.neighbourhood'),
        ),
    ]
