# Generated by Django 4.2.2 on 2023-08-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_consultant_scope_of_activity_from_ads_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='scope_of_activity_string',
            field=models.CharField(blank=True, editable=False, max_length=1000, null=True),
        ),
    ]
