# Generated by Django 4.2.2 on 2023-08-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_consultant_scope_of_activity_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم'),
        ),
    ]
