# Generated by Django 4.2.2 on 2023-08-06 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_consultant_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultant',
            options={'verbose_name': 'مشاور', 'verbose_name_plural': 'مشاورین املاک'},
        ),
        migrations.AlterModelOptions(
            name='estate',
            options={'verbose_name': 'ملک', 'verbose_name_plural': 'املاک'},
        ),
        migrations.AlterModelOptions(
            name='neighbourhood',
            options={'verbose_name': 'محله', 'verbose_name_plural': 'محله\u200cها'},
        ),
        migrations.AlterField(
            model_name='consultant',
            name='link',
            field=models.URLField(max_length=3000, verbose_name='لینک در دیوار'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='number_of_ads',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد اگهی ها'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='profile',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='پروفایل'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='عملکرد'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='scope_of_activity',
            field=models.ManyToManyField(to='home.neighbourhood', verbose_name='محدوده فعالیت'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='scope_of_activity_string',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='اخرین بروزرسانی اطلاعات'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estates', to='home.consultant', verbose_name='مشاور'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='link',
            field=models.URLField(max_length=2000, unique=True, verbose_name='لینک در دیوار'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='neighbourhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estates', to='home.neighbourhood', verbose_name='محله'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='متراژ'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='title',
            field=models.CharField(max_length=1000, unique=True, verbose_name='عنوان'),
        ),
    ]
